[1pt] PR: Clip ocean mask from DEM and extend outlet streams
NOAA-OWP/inundation-mapping pull request #1121
Opened 2024-04-15 14:43 UTC by mluck

Some NWM streams, particularly in coastal areas, fail to reach the edge of the DEM resulting in reverse flow (https://github.com/NOAA-OWP/inundation-mapping/issues/916#issuecomment-2010590913). This issue was resolved by clipping the ocean mask from the buffered WBD and DEM, and any remaining streams that didn't have outlets reaching the edge of the buffered WBD boundary were extended by snapping the end to the nearest point on the buffered WBD.

Note: this does not solve the issue noted at https://github.com/NOAA-OWP/hydrofabric/issues/38

### Changes

- `data/wbd/clip_vectors_to_wbd.py`: Clips `landsea` ocean mask from the buffered WBD and adds a function to extend outlet streams to the buffered WBD

### Testing
DEM before (left) and after (right) clipping the ocean mask from the buffered WBD
<img width="964" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/07eb4a79-655b-4d1a-ba8b-ff93aab19228">

Flow direction of DEM-derived reaches (red dashed lines) indicated by bold red arrows (before (left) and after (right))
<img width="978" alt="image" src="https://github.com/NOAA-OWP/inundation-mapping/assets/6616694/85765224-8dca-49d8-865d-d976a6455d55">

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- x ] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [x] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [ ] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [ ] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

2024-04-23 17:58 UTC, RobHanna-NOAA submitted a review, later dismissed
Matt helped show me the before and after. Looks good.

2024-04-23 22:44 UTC, RobHanna-NOAA approved these changes

2024-04-26 18:45 UTC, RobHanna-NOAA requested changes
During full scale testing, some errors occurred. It does appear that they only fail on HUC2 of 18 and higher but a full analysis was not done.

Here is an example of one fail (and each failing HUC has a different amount of the "Failed to auto identify EPSG: 7"

Full Error:
Get Vector Layers and Subset 19020103
Failed to auto identify EPSG: 7
Failed to auto identify EPSG: 7
Failed to auto identify EPSG: 7
Failed to auto identify EPSG: 7
Failed to auto identify EPSG: 7
Failed to auto identify EPSG: 7
Failed to auto identify EPSG: 7
Failed to auto identify EPSG: 7
Failed to auto identify EPSG: 7
Traceback (most recent call last):
  File "//./foss_fim/data/wbd/generate_pre_clip_fim_huc8.py", line 329, in huc_level_clip_vectors_to_wbd
    subset_vector_layers(
  File "/foss_fim/data/wbd/clip_vectors_to_wbd.py", line 240, in subset_vector_layers
    nwm_streams = extend_outlet_streams(nwm_streams, wbd_buffer, wbd)
  File "/foss_fim/data/wbd/clip_vectors_to_wbd.py", line 64, in extend_outlet_streams
    coords = [(coords) for coords in list(row['geometry'].coords)]
  File "/usr/local/lib/python3.10/dist-packages/shapely/geometry/base.py", line 910, in coords
    raise NotImplementedError(
NotImplementedError: Sub-geometries may have coordinate sequences, but multi-part geometries do not

Each HUC that had at least one EPSG: 7 failed with the sub-geometries error.

This is not a comprehensive list but some of the ones that failed are:18070305
18070201
19020401
18090101
18100203

and lots of others.
Doesn't appear there are any below 18's but not sure, might have been insufficent logging which was upgraded for the 18 and higher list.

2024-04-30 15:45 UTC, mluck commented
Strange, I just ran a couple of the problem HUCs and didn't have any errors:

```
/foss_fim/data/wbd/generate_pre_clip_fim_huc8.py -n /data/inputs/pre_clip_huc8/24_03_29 -u /data/inputs/huc_lists/test_hucs.lst -j 6 -o 
Created directory: /data/inputs/pre_clip_huc8/24_03_29/18070305, huc level files will be written there.
Created directory: /data/inputs/pre_clip_huc8/24_03_29/18070201, huc level files will be written there.
Generating vectors for 18070305. 
Generating vectors for 18070201. 
Parallelizing HUC level wbd pre-clip vector creation. 

 Get WBD 18070305

 Get WBD 18070201

 - Creating -- /data/inputs/pre_clip_huc8/24_03_29/18070305/wbd.gpkg - Complete 

Get Vector Layers and Subset 18070305
Getting Cell Size for 18070305

 - Creating -- /data/inputs/pre_clip_huc8/24_03_29/18070201/wbd.gpkg - Complete 

Get Vector Layers and Subset 18070201
Getting Cell Size for 18070201
Create wbd buffer for 18070305
Create wbd buffer for 18070201
Create landsea gpkg for 18070305
Create landsea gpkg for 18070201
Subsetting Levee Protected Areas for 18070201
Subsetting Levee Protected Areas for 18070305
Subsetting NWM Lakes for 18070201
Subsetting NLD levee lines for 18070201
Subsetting NWM Lakes for 18070305
Subsetting NLD levee lines for 18070305
Subsetting NWM Headwater Points for 18070305
Subsetting NWM Headwater Points for 18070201
Subsetting NWM Catchments for 18070201
Subsetting NWM Streams for 18070201

         Completing Get Vector Layers and Subset: 18070201 

 Clip WBD 18070201
Subsetting NWM Catchments for 18070305

 - Creating -- /data/inputs/pre_clip_huc8/24_03_29/18070201/wbd.gpkg - Complete
                 run time for huc 18070201: is 0:02:00
Subsetting NWM Streams for 18070305

         Completing Get Vector Layers and Subset: 18070305 

 Clip WBD 18070305

 - Creating -- /data/inputs/pre_clip_huc8/24_03_29/18070305/wbd.gpkg - Complete
                 run time for huc 18070305: is 0:03:12

         Completed writing all huc level files 

                 TOTAL RUN TIME: 0:03:13
```

2024-05-02 23:33 UTC, RobHanna-NOAA submitted a review, later dismissed

2024-05-06 20:32 UTC, CarsonPruitt-NOAA approved these changes

2024-05-06 20:32 UTC, merged